window.esdocSearchIndex = [
  [
    "serializerjs/src/serializer/abstractserializer.js~abstractserializer",
    "class/src/Serializer/AbstractSerializer.js~AbstractSerializer.html",
    "<span>AbstractSerializer</span> <span class=\"search-result-import-path\">serializerjs/src/Serializer/AbstractSerializer.js</span>",
    "class"
  ],
  [
    "serializerjs/src/error/invalidargumenterror.js~invalidargumenterror",
    "class/src/Error/InvalidArgumentError.js~InvalidArgumentError.html",
    "<span>InvalidArgumentError</span> <span class=\"search-result-import-path\">serializerjs/src/Error/InvalidArgumentError.js</span>",
    "class"
  ],
  [
    "serializerjs/src/error/serializationerror.js~serializationerror",
    "class/src/Error/SerializationError.js~SerializationError.html",
    "<span>SerializationError</span> <span class=\"search-result-import-path\">serializerjs/src/Error/SerializationError.js</span>",
    "class"
  ],
  [
    "serializerjs/src/serializer/serializer.js~serializer",
    "class/src/Serializer/Serializer.js~Serializer.html",
    "<span>Serializer</span> <span class=\"search-result-import-path\">serializerjs/src/Serializer/Serializer.js</span>",
    "class"
  ],
  [
    "serializerjs/src/serializer/serializeraware.js~serializeraware",
    "class/src/Serializer/SerializerAware.js~SerializerAware.html",
    "<span>SerializerAware</span> <span class=\"search-result-import-path\">serializerjs/src/Serializer/SerializerAware.js</span>",
    "class"
  ],
  [
    "serializerjs/src/error/serializererror.js~serializererror",
    "class/src/Error/SerializerError.js~SerializerError.html",
    "<span>SerializerError</span> <span class=\"search-result-import-path\">serializerjs/src/Error/SerializerError.js</span>",
    "class"
  ],
  [
    "serializerjs/src/serializer/serializerinterface.js~serializerinterface",
    "class/src/Serializer/SerializerInterface.js~SerializerInterface.html",
    "<span>SerializerInterface</span> <span class=\"search-result-import-path\">serializerjs/src/Serializer/SerializerInterface.js</span>",
    "class"
  ],
  [
    "serializerjs/src/error/unimplementedmethoderror.js~unimplementedserializermethoderror",
    "class/src/Error/UnimplementedMethodError.js~UnimplementedSerializerMethodError.html",
    "<span>UnimplementedSerializerMethodError</span> <span class=\"search-result-import-path\">serializerjs/src/Error/UnimplementedMethodError.js</span>",
    "class"
  ],
  [
    "abstractserializer src/serializer/abstractserializer.js~abstractserializer,abstractserializer",
    "test-file/tests/Serializer/AbstractSerializerTest.js.html#lineNumber18",
    "AbstractSerializer",
    "test"
  ],
  [
    "abstractserializer#constructor src/serializer/serializeraware.js~serializeraware#constructor,abstractserializer#constructor",
    "test-file/tests/Serializer/AbstractSerializerTest.js.html#lineNumber22",
    "AbstractSerializer It implements the SerializerInterface interface",
    "test"
  ],
  [
    "abstractserializer#supportsdeserialize abstractserializer#supportsserialize src/serializer/abstractserializer.js~abstractserializer#supportsdeserialize,abstractserializer#supportsdeserialize src/serializer/abstractserializer.js~abstractserializer#supportsserialize,abstractserializer#supportsserialize",
    "test-file/tests/Serializer/AbstractSerializerTest.js.html#lineNumber30",
    "AbstractSerializer It should not supports any (de)-serialization",
    "test"
  ],
  [
    "abstractserializer#deserialize abstractserializer#serialize src/serializer/abstractserializer.js~abstractserializer#deserialize,abstractserializer#deserialize src/serializer/abstractserializer.js~abstractserializer#serialize,abstractserializer#serialize",
    "test-file/tests/Serializer/AbstractSerializerTest.js.html#lineNumber41",
    "AbstractSerializer It should return the object unchanged if (de)-serialization is called [warning: bad practice]",
    "test"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "invalidargumenterror src/error/invalidargumenterror.js~invalidargumenterror,invalidargumenterror",
    "test-file/tests/Error/InvalidArgumentErrorErrorTest.js.html#lineNumber18",
    "SerializationError",
    "test"
  ],
  [
    "serializationerror src/error/serializationerror.js~serializationerror,serializationerror",
    "test-file/tests/Error/SerializerErrorTest.js.html#lineNumber17",
    "SerializationError",
    "test"
  ],
  [
    "serializationerror src/error/serializationerror.js~serializationerror,serializationerror",
    "test-file/tests/Error/SerializationErrorTest.js.html#lineNumber18",
    "SerializationError",
    "test"
  ],
  [
    "",
    "test-file/tests/Error/SerializerErrorTest.js.html#lineNumber30",
    "SerializationError An error without any message has an empty message",
    "test"
  ],
  [
    "",
    "test-file/tests/Error/SerializerErrorTest.js.html#lineNumber23",
    "SerializationError It captures the error message",
    "test"
  ],
  [
    "",
    "test-file/tests/Error/SerializerErrorTest.js.html#lineNumber36",
    "SerializationError It captures the error name",
    "test"
  ],
  [
    "",
    "test-file/tests/Error/SerializationErrorTest.js.html#lineNumber19",
    "SerializationError It is a SerializerError",
    "test"
  ],
  [
    "",
    "test-file/tests/Error/InvalidArgumentErrorErrorTest.js.html#lineNumber19",
    "SerializationError It is a SerializerError",
    "test"
  ],
  [
    "",
    "test-file/tests/Error/SerializerErrorTest.js.html#lineNumber18",
    "SerializationError It is an Error",
    "test"
  ],
  [
    "",
    "test-file/tests/Error/InvalidArgumentErrorErrorTest.js.html#lineNumber23",
    "SerializationError Its name is an InvalidArgumentError error",
    "test"
  ],
  [
    "",
    "test-file/tests/Error/SerializationErrorTest.js.html#lineNumber23",
    "SerializationError Its name is an SerializationError error",
    "test"
  ],
  [
    "serializer src/serializer/serializer.js~serializer,serializer",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber26",
    "Serializer",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber183",
    "Serializer If no serializer is found, should throw an error",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber88",
    "Serializer It can use the BooleanSerializer",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber89",
    "Serializer It can use the BooleanSerializer It should be able to deserialize a boolean value",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber97",
    "Serializer It can use the BooleanSerializer It should be able to deserialize a integer boolean value",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber105",
    "Serializer It can use the BooleanSerializer It should be able to deserialize a null value",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber110",
    "Serializer It can use the BooleanSerializer It should be able to serialize a boolean value",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber53",
    "Serializer It can use the StringSerializer",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber68",
    "Serializer It can use the StringSerializer It should be able to deserialize a null value",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber54",
    "Serializer It can use the StringSerializer It should be able to deserialize a string",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber61",
    "Serializer It can use the StringSerializer It should be able to deserialize an empty string",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber73",
    "Serializer It can use the StringSerializer It should be able to deserialize something else than a string or a null value",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber82",
    "Serializer It can use the StringSerializer It should not be able to serialize a string",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber146",
    "Serializer It can use the UserSerializer",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber161",
    "Serializer It can use the UserSerializer It should be able to deserialize a user object",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber174",
    "Serializer It can use the UserSerializer It should be able to serialize a User object",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber169",
    "Serializer It can use the UserSerializer It should not be able to deserialize a user object with another serializer",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber122",
    "Serializer It can use the UserTypeSerializer",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber123",
    "Serializer It can use the UserTypeSerializer It should be able to deserialize a UserType value",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber134",
    "Serializer It can use the UserTypeSerializer It should be able to serialize a UserType value",
    "test"
  ],
  [
    "serializer#constructor src/serializer/serializer.js~serializer#constructor,serializer#constructor",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber28",
    "Serializer It implements the SerializerInterface interface",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber32",
    "Serializer It should have a reference of all the registered serializers",
    "test"
  ],
  [
    "",
    "test-file/tests/Serializer/SerializerTest.js.html#lineNumber41",
    "Serializer Only serialiers can be registered",
    "test"
  ],
  [
    "serializeraware src/serializer/serializeraware.js~serializeraware,serializeraware",
    "test-file/tests/Serializer/SerializerAwareTest.js.html#lineNumber19",
    "SerializerAware",
    "test"
  ],
  [
    "serializeraware#constructor src/serializer/serializeraware.js~serializeraware#constructor,serializeraware#constructor",
    "test-file/tests/Serializer/SerializerAwareTest.js.html#lineNumber21",
    "SerializerAware It implements the SerializerInterface interface",
    "test"
  ],
  [
    "serializeraware#setserializer src/serializer/serializeraware.js~serializeraware#setserializer,serializeraware#setserializer",
    "test-file/tests/Serializer/SerializerAwareTest.js.html#lineNumber26",
    "SerializerAware It should contain a reference to the serializer",
    "test"
  ],
  [
    "serializerinterface src/serializer/serializerinterface.js~serializerinterface,serializerinterface",
    "test-file/tests/Serializer/SerializerInterfaceTest.js.html#lineNumber18",
    "SerializerInterface",
    "test"
  ],
  [
    "serializerinterface#deserialize serializerinterface#serialize serializerinterface#supportsdeserialize serializerinterface#supportsserialize src/serializer/serializerinterface.js~serializerinterface#deserialize,serializerinterface#deserialize src/serializer/serializerinterface.js~serializerinterface#serialize,serializerinterface#serialize src/serializer/serializerinterface.js~serializerinterface#supportsdeserialize,serializerinterface#supportsdeserialize src/serializer/serializerinterface.js~serializerinterface#supportsserialize,serializerinterface#supportsserialize",
    "test-file/tests/Serializer/SerializerInterfaceTest.js.html#lineNumber25",
    "SerializerInterface As an interface, it should not implement anything",
    "test"
  ],
  [
    "src/error/invalidargumenterror.js",
    "file/src/Error/InvalidArgumentError.js.html",
    "src/Error/InvalidArgumentError.js",
    "file"
  ],
  [
    "src/error/invalidargumenterror.js~invalidargumenterror#constructor",
    "class/src/Error/InvalidArgumentError.js~InvalidArgumentError.html#instance-constructor-constructor",
    "src/Error/InvalidArgumentError.js~InvalidArgumentError#constructor",
    "method"
  ],
  [
    "src/error/invalidargumenterror.js~invalidargumenterror#name",
    "class/src/Error/InvalidArgumentError.js~InvalidArgumentError.html#instance-member-name",
    "src/Error/InvalidArgumentError.js~InvalidArgumentError#name",
    "member"
  ],
  [
    "src/error/serializationerror.js",
    "file/src/Error/SerializationError.js.html",
    "src/Error/SerializationError.js",
    "file"
  ],
  [
    "src/error/serializationerror.js~serializationerror#constructor",
    "class/src/Error/SerializationError.js~SerializationError.html#instance-constructor-constructor",
    "src/Error/SerializationError.js~SerializationError#constructor",
    "method"
  ],
  [
    "src/error/serializationerror.js~serializationerror#name",
    "class/src/Error/SerializationError.js~SerializationError.html#instance-member-name",
    "src/Error/SerializationError.js~SerializationError#name",
    "member"
  ],
  [
    "src/error/serializererror.js",
    "file/src/Error/SerializerError.js.html",
    "src/Error/SerializerError.js",
    "file"
  ],
  [
    "src/error/serializererror.js~serializererror#constructor",
    "class/src/Error/SerializerError.js~SerializerError.html#instance-constructor-constructor",
    "src/Error/SerializerError.js~SerializerError#constructor",
    "method"
  ],
  [
    "src/error/serializererror.js~serializererror#message",
    "class/src/Error/SerializerError.js~SerializerError.html#instance-member-message",
    "src/Error/SerializerError.js~SerializerError#message",
    "member"
  ],
  [
    "src/error/serializererror.js~serializererror#name",
    "class/src/Error/SerializerError.js~SerializerError.html#instance-member-name",
    "src/Error/SerializerError.js~SerializerError#name",
    "member"
  ],
  [
    "src/error/unimplementedmethoderror.js",
    "file/src/Error/UnimplementedMethodError.js.html",
    "src/Error/UnimplementedMethodError.js",
    "file"
  ],
  [
    "src/error/unimplementedmethoderror.js~unimplementedserializermethoderror#constructor",
    "class/src/Error/UnimplementedMethodError.js~UnimplementedSerializerMethodError.html#instance-constructor-constructor",
    "src/Error/UnimplementedMethodError.js~UnimplementedSerializerMethodError#constructor",
    "method"
  ],
  [
    "src/error/unimplementedmethoderror.js~unimplementedserializermethoderror#name",
    "class/src/Error/UnimplementedMethodError.js~UnimplementedSerializerMethodError.html#instance-member-name",
    "src/Error/UnimplementedMethodError.js~UnimplementedSerializerMethodError#name",
    "member"
  ],
  [
    "src/serializer/abstractserializer.js",
    "file/src/Serializer/AbstractSerializer.js.html",
    "src/Serializer/AbstractSerializer.js",
    "file"
  ],
  [
    "src/serializer/abstractserializer.js~abstractserializer#deserialize",
    "class/src/Serializer/AbstractSerializer.js~AbstractSerializer.html#instance-method-deserialize",
    "src/Serializer/AbstractSerializer.js~AbstractSerializer#deserialize",
    "method"
  ],
  [
    "src/serializer/abstractserializer.js~abstractserializer#serialize",
    "class/src/Serializer/AbstractSerializer.js~AbstractSerializer.html#instance-method-serialize",
    "src/Serializer/AbstractSerializer.js~AbstractSerializer#serialize",
    "method"
  ],
  [
    "src/serializer/abstractserializer.js~abstractserializer#supportsdeserialize",
    "class/src/Serializer/AbstractSerializer.js~AbstractSerializer.html#instance-method-supportsDeserialize",
    "src/Serializer/AbstractSerializer.js~AbstractSerializer#supportsDeserialize",
    "method"
  ],
  [
    "src/serializer/abstractserializer.js~abstractserializer#supportsserialize",
    "class/src/Serializer/AbstractSerializer.js~AbstractSerializer.html#instance-method-supportsSerialize",
    "src/Serializer/AbstractSerializer.js~AbstractSerializer#supportsSerialize",
    "method"
  ],
  [
    "src/serializer/serializer.js",
    "file/src/Serializer/Serializer.js.html",
    "src/Serializer/Serializer.js",
    "file"
  ],
  [
    "src/serializer/serializer.js~serializer#constructor",
    "class/src/Serializer/Serializer.js~Serializer.html#instance-constructor-constructor",
    "src/Serializer/Serializer.js~Serializer#constructor",
    "method"
  ],
  [
    "src/serializer/serializer.js~serializer#deserialize",
    "class/src/Serializer/Serializer.js~Serializer.html#instance-method-deserialize",
    "src/Serializer/Serializer.js~Serializer#deserialize",
    "method"
  ],
  [
    "src/serializer/serializer.js~serializer#serialize",
    "class/src/Serializer/Serializer.js~Serializer.html#instance-method-serialize",
    "src/Serializer/Serializer.js~Serializer#serialize",
    "method"
  ],
  [
    "src/serializer/serializer.js~serializer#supportsdeserialize",
    "class/src/Serializer/Serializer.js~Serializer.html#instance-method-supportsDeserialize",
    "src/Serializer/Serializer.js~Serializer#supportsDeserialize",
    "method"
  ],
  [
    "src/serializer/serializer.js~serializer#supportsserialize",
    "class/src/Serializer/Serializer.js~Serializer.html#instance-method-supportsSerialize",
    "src/Serializer/Serializer.js~Serializer#supportsSerialize",
    "method"
  ],
  [
    "src/serializer/serializeraware.js",
    "file/src/Serializer/SerializerAware.js.html",
    "src/Serializer/SerializerAware.js",
    "file"
  ],
  [
    "src/serializer/serializeraware.js~serializeraware#_serializer",
    "class/src/Serializer/SerializerAware.js~SerializerAware.html#instance-member-_serializer",
    "src/Serializer/SerializerAware.js~SerializerAware#_serializer",
    "member"
  ],
  [
    "src/serializer/serializeraware.js~serializeraware#constructor",
    "class/src/Serializer/SerializerAware.js~SerializerAware.html#instance-constructor-constructor",
    "src/Serializer/SerializerAware.js~SerializerAware#constructor",
    "method"
  ],
  [
    "src/serializer/serializeraware.js~serializeraware#setserializer",
    "class/src/Serializer/SerializerAware.js~SerializerAware.html#instance-method-setSerializer",
    "src/Serializer/SerializerAware.js~SerializerAware#setSerializer",
    "method"
  ],
  [
    "src/serializer/serializerinterface.js",
    "file/src/Serializer/SerializerInterface.js.html",
    "src/Serializer/SerializerInterface.js",
    "file"
  ],
  [
    "src/serializer/serializerinterface.js~serializerinterface#deserialize",
    "class/src/Serializer/SerializerInterface.js~SerializerInterface.html#instance-method-deserialize",
    "src/Serializer/SerializerInterface.js~SerializerInterface#deserialize",
    "method"
  ],
  [
    "src/serializer/serializerinterface.js~serializerinterface#serialize",
    "class/src/Serializer/SerializerInterface.js~SerializerInterface.html#instance-method-serialize",
    "src/Serializer/SerializerInterface.js~SerializerInterface#serialize",
    "method"
  ],
  [
    "src/serializer/serializerinterface.js~serializerinterface#supportsdeserialize",
    "class/src/Serializer/SerializerInterface.js~SerializerInterface.html#instance-method-supportsDeserialize",
    "src/Serializer/SerializerInterface.js~SerializerInterface#supportsDeserialize",
    "method"
  ],
  [
    "src/serializer/serializerinterface.js~serializerinterface#supportsserialize",
    "class/src/Serializer/SerializerInterface.js~SerializerInterface.html#instance-method-supportsSerialize",
    "src/Serializer/SerializerInterface.js~SerializerInterface#supportsSerialize",
    "method"
  ],
  [
    "src/serializerjs.js",
    "file/src/serializerjs.js.html",
    "src/serializerjs.js",
    "file"
  ],
  [
    "tests/error/invalidargumenterrorerrortest.js",
    "test-file/tests/Error/InvalidArgumentErrorErrorTest.js.html",
    "tests/Error/InvalidArgumentErrorErrorTest.js",
    "testFile"
  ],
  [
    "tests/error/serializationerrortest.js",
    "test-file/tests/Error/SerializationErrorTest.js.html",
    "tests/Error/SerializationErrorTest.js",
    "testFile"
  ],
  [
    "tests/error/serializererrortest.js",
    "test-file/tests/Error/SerializerErrorTest.js.html",
    "tests/Error/SerializerErrorTest.js",
    "testFile"
  ],
  [
    "tests/serializer/abstractserializertest.js",
    "test-file/tests/Serializer/AbstractSerializerTest.js.html",
    "tests/Serializer/AbstractSerializerTest.js",
    "testFile"
  ],
  [
    "tests/serializer/serializerawaretest.js",
    "test-file/tests/Serializer/SerializerAwareTest.js.html",
    "tests/Serializer/SerializerAwareTest.js",
    "testFile"
  ],
  [
    "tests/serializer/serializerinterfacetest.js",
    "test-file/tests/Serializer/SerializerInterfaceTest.js.html",
    "tests/Serializer/SerializerInterfaceTest.js",
    "testFile"
  ],
  [
    "tests/serializer/serializertest.js",
    "test-file/tests/Serializer/SerializerTest.js.html",
    "tests/Serializer/SerializerTest.js",
    "testFile"
  ]
]